
#rel static settings from production
#real databasename from productioln settings


"""
Django settings for restingblog project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
import os
from .base import *

#production settings live here


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sou0$-u#=r^&315#-^hr!+^-107jss#3nb$3#4)ep+iea6u9(n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ADMINS = (
    #("Admin_name", "Admin email address"),
    ("Boiyelove", "daahrmmieboiye@gmail.com"),
    )

ALLOWED_HOSTS = ['www.boiyelabs.com', 'boiyelabs.com']

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'yourgmail@gmail.com'
EMAIL_HOST_PASSWORD = 'yourpassword'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

    ''' 
If using gmail, you will need to
unlock Captcha to enable Django 
to  send for you:
https://accounts.google.com/displayunlockcaptcha
'''



MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restingblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.ath.join(BASE_DRI, 'tenplates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restingblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
#database passwords are kept in db_password.py and are imported into the settings file
#As defined below, host, name, port, user, password are optional
from .db_password import firstdbpass, seconddbpass, thirddbpass, forthdbpass
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
    # settings for the first database oracle
    'firstdsb': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'my_database',
        'HOST': '',
        'PORT': '',
        'USER': '',
        'PASSWORD': firstdbpass,
    
    }
    # settings for the second database mysql
    'secondb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_database',
        'HOST': '',
        'PORT': '',
        'USER': '',
        'PASSWORD': seconddb,
        
    }
    # settings for the third database oracle 
    'thirddb': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'my_database',
        'HOST': '',
        'PORT': '',
        'USER': '',
        'PASSWORD': thirddbpass,
    
    }
    # settings for the fourth database: mongodb
    'forthdb': {
        'ENGINE': 'django_mongodb_engine',
        'NAME': 'my_database',
        'HOST': '',
        'PORT': '',
        'USER': '',
        'PASSWORD': forthdbpass,
    }
    # settings for the fourth database: mongodb
    'replica': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myproject',
        'HOST': 'dbreplica',
        'TEST': {
            'MIRROR': 'default',
        },
        # ... plus some other settings
    }
}



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/home/username/webapps/webapp_name/'
#os.path.join(os.path.dirname(BASE_DIR), "static_in_env", "static_root")

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "pstatic"),
    #os.path.join(BASE_DIR, "static_in_env"),
    #'/var/www/static/',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/username/webapps/webapp_name/'
#os.path.join(os.path.dirname(BASE_DIR), "static_in_env", "media_root")



